---
# Action to perform: One of: "deploy", "destroy".
manage_containers_action: "deploy"

deploy_containers_defaults:
  comparisons:
    image: strict
    env: strict
    volumes: strict
  detach: True
  network_mode: "host"
  init: True
  privileged: False
  restart_policy: "unless-stopped"

deploy_containers_containers: []

deploy_containers_docker_api_timeout: 120

deploy_containers_registry:
deploy_containers_registry_username:
deploy_containers_registry_password:

deploy_containers_registry_attempt_login: "{{ deploy_containers_registry_username is truthy and deploy_containers_registry_password is truthy }}"
