---
- name: "Ensure defined container images are {{ kayobe_action | default('deploy') }}ed on overcloud nodes"
  hosts: overcloud
  tags:
    - controller-deploy-containers
    - controller-manage-containers
  vars:
    manage_containers_action: "{{ kayobe_action | default('deploy') }}"
  roles:
    - role: manage-containers
